= SBUILD(1)
:doctype: manpage
Tobias Roeser <le.petit.fou@web.de>
:man manual: SBuild Manual

== NAME

sbuild - Execute a buildscript

== SYNOPSIS

*sbuild* [OPTIONS] TARGET*

== DESCRIPTION

SBuild is a build tool.

== TARGET

A target to be executed.

== OPTIONS

  --additional-buildfile,-F FILE  Add an additional buildfile into scope.
  --buildfile,-f FILE             The buildfile to use (default: SBuild.scala).
  --check                         Check targets for cycles and missing scheme
                                  handlers.
  --check-recursive               Check targets of this project and all its
                                  modules for cycles and missing scheme
                                  handlers.
  --clean                         Remove all generated output and caches. This
                                  will force a new compile of the buildfile.
                                  (This will not remove output generated by
                                  buildfiles.)
  --create-stub                   Create a new minimal SBuild.scala file to
                                  start with.
  --define,-D KEY=VALUE           Define or override properties. If VALUE is
                                  omitted it defaults to "true".
  --dependency-tree               Show dependency tree(s) and exit.
  --execution-plan                Show the execution plan and exit.
  --fsc                           Use the fast scala compiler (client/server).
                                  The fsc compiler of the correct Scala version
                                  must be installed.
  --help,-h                       Show this help screen.
  --jobs,-j N                     Allow processing N targets in parallel.
  --just-clean                    Remove all generated output and caches without
                                  reading any buildfile. This will essentially
                                  remove the ".sbuild" directory in the current
                                  directory.
  --just-clean-recursive          Remove all generated output and caches without
                                  reading any buildfile. This will essentially
                                  remove the ".sbuild" directory in the current
                                  directory and all sub-directories, no matter,
                                  if sub-directories contain SBuild projects or
                                  not.
  --list-modules                  Show a list of modules involved in this
                                  project.
  --list-targets,-l               Show a list of targets defined in the current
                                  buildfile.
  --list-targets-recursive,-L     Show a list of targets defined in the current
                                  buildfile and all modules.
  --no-color                      Disable colored output.
  --no-fsc                        Do not try to use the fast scala compiler
                                  (client/server)
  --no-global                     Do not read global settings from <USER
                                  HOME>/.sbuildrc.
  -q,--quiet,--no-progress        Quiet mode. Don't show progress messages with
                                  progress in percent. (This will speed up
                                  SBuild initialization.)
  --repeat SECONDS                Repeat the requested action after the given
                                  time (in seconds), but not before the previous
                                  run was completed.
  --verbose,-v                    Be verbose when running.
  --version                       Show SBuild version.

