language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  - SBUILD_VERSION=0.7.1
  - SBUILD_VERSION=0.7.6

before_script: "./sbuild-wrapper --version"

script: "./sbuild-wrapper --keep-going all"

notifications:
  irc: "irc.freenode.org#sbuild"
