language: java

jdk:
  - oraclejdk7
  - openjdk7

env:
  - SBUILD_VERSION=0.7.1

before_script: "./sbuild-wrapper --version"

script: "./sbuild-wrapper all"

notifications:
  irc: "irc.freenode.org#sbuild"
