language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

env:
  - SBUILD_VERSION=0.6.0
  - SBUILD_VERSION=0.7.0
  - SBUILD_VERSION=0.7.1
  - SBUILD_VERSION=0.7.3

matrix:
  exclude:
    - jdk: openjdk6
      env: SBUILD_VERSION=0.7.0
    - jdk: openjdk6
      env: SBUILD_VERSION=0.7.1

install: "sudo apt-get install asciidoc"

before_script: "./sbuild-wrapper --version"

script: "./sbuild-wrapper --jobs 4 all"

notifications:
  irc: "irc.freenode.org#sbuild"
