language: java

jdk:
  - oraclejdk7
  - openjdk7

env:
  matrix:
    - SBUILD_VERSION=0.6.0
    - SBUILD_VERSION=0.7.1
    - SBUILD_VERSION=0.7.6

install: "sudo apt-get install asciidoc"

before_script: "./sbuild-wrapper --version"

script: "./sbuild-wrapper --jobs 4 all"

notifications:
  irc: "irc.freenode.org#sbuild"
