= SBuild 

SBuild is a very fast, powerful and flexible build tool. It can be used to build anything you want and does not force any style, but its main target are all Java VM targeted projects. The main "script language" of SBuild is Scala. SBuild is a dependency-driven tool, so it will only do what is necessary, to build your requested target, nothing more and nothing less. SBuild can detect unchanged targets and dependencies, and will avoid doing the same task multiple times, if nothing has changed.

The project home page is: http://sbuild.tototec.de

== How to build SBuild

SBuild is build with a previously released stable version of SBuild itself.

To build SBuild from source, you need to clone SBuild's git repository. After changing into the newly created directory "sbuild", you should use the "sbuild-wrapper" script in the project directory to build sbuild. When executing sbuild-wrapper the first time, it will download the right version of SBuild and will use it.

----
git clone https://github.com/SBuild-org/sbuild.git
cd sbuild
./sbuild-wrapper all
----

To build everything, including executing the tests, you should use the "all" target.

== Contributions

We 're glad to welcome any kind of feedback and contributions. 

Currently, we are in the transition from the Redmine-based project site to a Github + Static Pages approach.
Our goal is, to migrate all existing tickets to Github issue tracker.
Thus, we currently disabled issues + PR submissions on Github. 
Please use the Redmine site at http://sbuild.tototec.de/sbuild for now. Thank you!
