#!/bin/sh

VERSION="0.6.0"
SRC="http://sbuild.tototec.de/sbuild/attachments/download/75/sbuild-0.6.0-dist.zip"

if [ -d ".wrapper/sbuild-${VERSION}" ] ; then
  echo "Using SBuild ${VERSION}"
else
  echo "Fetching SBuild ${VERSION}"
  mkdir -p ".wrapper"
  (cd .wrapper && wget "${SRC}")
  (cd .wrapper && unzip "sbuild-${VERSION}-dist.zip")
  chmod u+x ".wrapper/sbuild-${VERSION}/bin/sbuild"
fi

exec ".wrapper/sbuild-${VERSION}/bin/sbuild" "$@"
